/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.mvc;

//import static org.testng.Assert.*;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
